name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'README.md'

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  smoke-test:
    name: Smoke test
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-22.04 ]
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --omit=optional
      - name: Build workspaces
        run: npm run build -ws
      - name: Remove dev dependencies
        run: npm prune --omit=dev
      - name: Run CommonJS module smoke test
        run: DEBUG=testcontainers* node packages/testcontainers/smoke-tests/commonjs.js
      - name: Run ES module smoke test
        run: DEBUG=testcontainers* node packages/testcontainers/smoke-tests/esm.mjs

  smoke-test-tcc-turbo-mode:
    name: Smoke test TCC turbo mode
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-22.04 ]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
          args: --max-concurrency=4
      - name: Install NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --omit=optional
      - name: Build workspaces
        run: npm run build -ws
      - name: Remove dev dependencies
        run: npm prune --omit=dev
      - name: Run TCC turbo mode smoke test
        run: |
          seq 4 | parallel --lb --halt now,fail=1 \
            "DEBUG=testcontainers* node packages/testcontainers/smoke-tests/tcc-turbo-mode.mjs"

  test-testcontainers:
    name: Testcontainers
    needs:
      - smoke-test
      - smoke-test-tcc-turbo-mode
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
        container-runtime: [ docker, docker-rootless, podman ]
        include:
          - container-runtime: docker
            runner: ubuntu-22.04
          - container-runtime: docker-rootless
            runner: ubuntu-22.04
          - container-runtime: podman
            runner: ubuntu-22.04
    uses: ./.github/workflows/test-template.yml
    with:
      runner: ${{ matrix.runner }}
      node-version: ${{ matrix.node-version }}
      container-runtime: ${{ matrix.container-runtime }}
      workspace: packages/testcontainers

  test-modules:
    name: Module (${{ matrix.module }})
    needs: test-testcontainers
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
        container-runtime: [ docker, docker-rootless, podman ]
        include:
          - container-runtime: docker
            runner: ubuntu-22.04
          - container-runtime: docker-rootless
            runner: ubuntu-22.04
          - container-runtime: podman
            runner: ubuntu-22.04
        module:
          - arangodb
          - elasticsearch
          - hivemq
          - kafka
          - mongodb
          - mysql
          - nats
          - neo4j
          - postgresql
          - selenium
    uses: ./.github/workflows/test-template.yml
    with:
      runner: ${{ matrix.runner }}
      node-version: ${{ matrix.node-version }}
      container-runtime: ${{ matrix.container-runtime }}
      workspace: packages/modules/${{ matrix.module }}
